In [24]:
import gensim
import os
import collections
import smart_open
import random
import json
from gensim.test.utils import get_tmpfile
from gensim.utils import simple_preprocess as preprocess
import numpy as np

In [4]:
fname = get_tmpfile("/Users/LYB/Desktop/coursework/Msc-project/vision_and_nlp/dataset/recipeQA/recipe_simple/impatient_reader/my_doc2vec_model")
model = gensim.models.doc2vec.Doc2Vec.load(fname) 

In [96]:
def load_cleaned_data(file = 'train_cleaned.json'):
    file = open(file, 'r', encoding='utf8').read()
    recipe = json.loads(file) #json file contains data in str, convert str to dict
    recipe_context = recipe['context']
    recipe_answer = recipe['answer']
    recipe_choice = recipe['choice']
    recipe_question = recipe['question']
    recipe_images = recipe['images']
    return recipe_context, recipe_images, recipe_question, recipe_choice, recipe_answer 
recipe_context, recipe_images, recipe_question, recipe_choice, recipe_answer = load_cleaned_data('train_cleaned.json')
recipe_context_valid, recipe_images_valid, recipe_question_valid, recipe_choice_valid, recipe_answer_valid = load_cleaned_data('val_cleaned.json')

In [97]:
recipe_context_train = recipe_context

In [ ]:
true_answer = []
for i in range(len(recipe_answer)):
    true_answer.append(recipe_choice[i][recipe_answer[i]]) 
false_answer = []
for i in range(len(recipe_answer)):
    false_answer.append(recipe_choice[i][:recipe_answer[i]]+ recipe_choice[i][(recipe_answer[i]+1):]) 
random_choice_false_answer = []
for i in range(len(false_answer)):
    random_choice_false_answer.append(np.random.choice(false_answer[i]))
recipe_question_true = []
for i in range(len(recipe_question)):
    temp = []
    for j in recipe_question[i]:
        if j == '@placeholder':
            temp.append(true_answer[i])
        else:
            temp.append(j)
    recipe_question_true.append(temp)
recipe_question_false = []
for i in range(len(recipe_question)):
    temp = []
    for j in recipe_question[i]:
        if j == '@placeholder':
            temp.append(random_choice_false_answer[i])
        else:
            temp.append(j)
    recipe_question_false.append(temp)

In [18]:
true_answer = []
for i in range(len(recipe_answer)):
    true_answer.append(recipe_choice[i][recipe_answer[i]]) 

In [22]:
false_answer = []
for i in range(len(recipe_answer)):
    false_answer.append(recipe_choice[i][:recipe_answer[i]]+ recipe_choice[i][(recipe_answer[i]+1):]) 

In [34]:
random_choice_false_answer = []
for i in range(len(false_answer)):
    random_choice_false_answer.append(np.random.choice(false_answer[i]))

In [40]:
recipe_question_true = []
for i in range(len(recipe_question)):
    temp = []
    for j in recipe_question[i]:
        if j == '@placeholder':
            temp.append(true_answer[i])
        else:
            temp.append(j)
    recipe_question_true.append(temp)

In [45]:
recipe_question_false = []
for i in range(len(recipe_question)):
    temp = []
    for j in recipe_question[i]:
        if j == '@placeholder':
            temp.append(random_choice_false_answer[i])
        else:
            temp.append(j)
    recipe_question_false.append(temp)

In [98]:
a = recipe_context_train[:5]

In [101]:
new = []
for i in range(len(a)):
    temp = []
    for j in range(len(a[i])):
        temp.append(model.infer_vector(a[i][j]))
    new.append(torch.FloatTensor(temp))

In [104]:
new = torch.nn.utils.rnn.pad_sequence(new, batch_first=False, padding_value=0)

In [105]:
new.size() 

torch.Size([9, 5, 100])

In [50]:
model.infer_vector(recipe_context_train)

array([ 0.33171582, -0.35106367,  0.00987989, -0.22751588, -0.16722651,
       -0.23928583,  0.11541141,  0.16202833,  0.13852815,  0.48238418,
       -0.03862878,  0.67951334, -0.01723733,  0.09269883, -0.5091477 ,
        0.07707996, -0.25180283, -0.08314572,  0.18197103, -0.17933787,
       -0.51753   ,  0.23488383, -0.2270024 ,  0.12943152, -0.1495811 ,
       -0.16249223, -0.24429478, -0.11015987,  0.16466998, -0.02926765,
       -0.09842672,  0.19147064,  0.06427644,  0.23581955, -0.3282941 ,
       -0.31158888,  0.06404398, -0.00277017, -0.22398058, -0.05657823,
        0.0608694 ,  0.14243686,  0.03196848,  0.0227991 ,  0.201124  ,
        0.06489012, -0.35791418, -0.16160522,  0.0387137 ,  0.24411638,
        0.126013  ,  0.39578348,  0.11023561,  0.08496653, -0.08845673,
        0.19299418,  0.02864688,  0.00390035,  0.18257846, -0.0375069 ,
        0.4073455 , -0.06528626, -0.20344757, -0.00409663,  0.12631267,
        0.03148993,  0.39479324,  0.37450305, -0.11695344, -0.45

In [139]:
recipe_question_true[:5]

[['Ingredients Halal Vanilla Extract',
  'Scrape Vanilla Beans',
  'Vegetable Glycerin and Vanilla Beans',
  'Vanilla Beans Can Use With Vegetable Glycerin'],
 ['Into the Blender.',
  'Time to Add the Beet Juice.',
  'Cover and Blend.',
  'Serving Suggestions and Tips.'],
 ['Cut the Pumpkin in Half',
  'Steam in the Oven',
  'Scrape Out Cooked Pumpkin',
  'Toast the Seeds (Optional)'],
 ['Prepare the Dough',
  'Shape the Gnocchi',
  'Prepare the Sauce',
  'Cook the Gnocchi and Mix Everything Together'],
 ['Stuffing Ingredients',
  'Simmer the Stuffing',
  'Prepare the Dough',
  'Prepare the Pan']]

In [138]:
recipe_question_false[:5]

[['Ingredients Halal Vanilla Extract',
  'Scrape Vanilla Beans',
  'Vegetable Glycerin and Vanilla Beans',
  'Prepare the Dough'],
 ['How to Make Bannock',
  'Time to Add the Beet Juice.',
  'Cover and Blend.',
  'Serving Suggestions and Tips.'],
 ['Cut the Pumpkin in Half',
  'The Pumpkins',
  'Scrape Out Cooked Pumpkin',
  'Toast the Seeds (Optional)'],
 ['Prepare the Sabayon',
  'Shape the Gnocchi',
  'Prepare the Sauce',
  'Cook the Gnocchi and Mix Everything Together'],
 ['Assemble the Burger & EAT!',
  'Simmer the Stuffing',
  'Prepare the Dough',
  'Prepare the Pan']]

In [135]:
b = recipe_question[0:5] 

In [136]:
b

[['Ingredients Halal Vanilla Extract',
  'Scrape Vanilla Beans',
  'Vegetable Glycerin and Vanilla Beans',
  '@placeholder'],
 ['@placeholder',
  'Time to Add the Beet Juice.',
  'Cover and Blend.',
  'Serving Suggestions and Tips.'],
 ['Cut the Pumpkin in Half',
  '@placeholder',
  'Scrape Out Cooked Pumpkin',
  'Toast the Seeds (Optional)'],
 ['@placeholder',
  'Shape the Gnocchi',
  'Prepare the Sauce',
  'Cook the Gnocchi and Mix Everything Together'],
 ['@placeholder',
  'Simmer the Stuffing',
  'Prepare the Dough',
  'Prepare the Pan']]

In [132]:
c = []
for i in range(len(b)): 
    c.append(model.infer_vector(' '.join(b[i]).split()))
c = torch.FloatTensor(c)

In [134]:
c.size()

torch.Size([5, 100])

In [123]:
new = []
for i in range(len(b)):
    temp = []
    for j in range(len(b[i])):
        temp.append(model.infer_vector(b[i][j].split()))
    new.append(temp)
new = torch.FloatTensor(new).permute(1, 0, 2)

In [117]:
new = torch.FloatTensor(new).permute(1, 0, 2)

In [120]:
new = new.permute(1, 0, 2).size()

torch.Size([4, 5, 100])

In [141]:
def cosine_dot_distance(x1, x2):
    return torch.sum(torch.mul(x1, x2), dim=1)

In [151]:
import torch.nn.functional as F
input1 = torch.randn(5, 128)
input2 = torch.randn(5, 128)
output = F.cosine_similarity(input1, input2)
print(output) 

tensor([0.0280, 0.0416, 0.1578, 0.0663, 0.1427])


In [146]:
x1 = torch.randn(5, 100)

In [148]:
x2 = torch.randn(5, 100)

In [149]:
cosine_dot_distance(x1,x2)

tensor([ -7.1869,  20.0824,  -1.0121,  -4.3064, -16.6797])

In [153]:
c = recipe_choice[0:5]

In [154]:
input_new = []
for i in range(len(c)):
    temp = []
    for j in range(len(c[i])):
        temp.append(model.infer_vector(c[i][j].lower().split())) 
    input_new.append(temp) 
input_new = torch.FloatTensor(input_new).permute(1, 0, 2)

In [206]:
recipe_choice[0:5]

[['How to Make Caffe Mocha',
  'How to Make Koki Paratha',
  'Vanilla Beans Can Use With Vegetable Glycerin',
  'Prepare the Dough'],
 ['How to Make Bannock', 'Brown the Meat', 'Into the Blender.', 'Optional'],
 ['Easy Holiday Pumpkin Mousse',
  'Fresh Pumpkin Puree',
  'The Pumpkins',
  'Steam in the Oven'],
 ['A',
  'Filling the Paper Sweet Cases',
  'Prepare the Dough',
  'Prepare the Sabayon'],
 ['so',
  'Grill the Burgers',
  'Assemble the Burger & EAT!',
  'Stuffing Ingredients']]

In [207]:
recipe_context[0:5]

[[['3',
   'until',
   '5',
   'whole',
   'vanilla',
   'beans250',
   'gram',
   'of',
   'vegetable',
   'glycerin',
   'food',
   'gradeevery',
   '100',
   'gram',
   'of',
   'vanilla',
   'beans',
   'have',
   '35',
   'until',
   '40',
   'of',
   'whole',
   'vanilla',
   'beans'],
  ['scrape',
   'vanilla',
   'beans',
   'and',
   'get',
   'the',
   'seeds',
   'into',
   'vegetable',
   'glycerin'],
  ['vanilla', 'beans', 'seed', 'and', 'vegetable', 'glycerin'],
  ['whole',
   'vanilla',
   'beans',
   'put',
   'in',
   'a',
   'bottle',
   'with',
   'seeds',
   'and',
   'vegetable',
   'glycerin']],
 [['there',
   'are',
   'many',
   'variants',
   'of',
   'borscht',
   'this',
   'is',
   'possibly',
   'one',
   'of',
   'the',
   'quickest',
   'and',
   'easy',
   'versions',
   'for',
   'it',
   'you',
   'will',
   'need',
   'ingredients',
   '4',
   'cups',
   'of',
   'chilled',
   'sliced',
   'beets',
   'two',
   '16oz',
   'cans',
   '1',
   '1',
   '2

In [156]:
input_new.size()

torch.Size([4, 5, 100])

In [ ]:
similarity_scores = F.cosine_similarity(input1, input2)

In [161]:
a = np.random.randn(4,5)

In [163]:
torch.FloatTensor(a, requires_grad=True)

TypeError: new() received an invalid combination of arguments - got (numpy.ndarray, requires_grad=bool), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad


In [177]:
torch.randn(100, 128, requires_grad=False)

tensor([[ 1.0447,  0.5297,  0.9000,  ...,  0.1185,  0.8013, -0.8433],
        [ 0.6727,  1.2909,  0.4010,  ...,  0.1658,  0.4739, -0.4884],
        [ 0.7699,  0.0029,  0.7224,  ..., -0.3338, -0.2624,  0.8344],
        ...,
        [-0.3780,  0.0435,  1.9097,  ..., -0.2431, -0.8318,  0.2705],
        [ 2.3637, -1.1103, -0.0328,  ...,  0.6527, -0.0085,  1.0692],
        [-1.3139, -0.0294, -2.0281,  ...,  0.5292, -0.6514,  0.1403]])

In [178]:
torch.randn(100, 128, requires_grad=True)

tensor([[ 0.8069, -2.0263, -0.6696,  ..., -0.5949, -0.1640,  1.8887],
        [-0.9242, -0.6868,  2.2427,  ..., -0.4380, -1.2344,  1.9001],
        [-1.0531,  0.3368, -0.8414,  ...,  1.4221, -0.3786, -0.1016],
        ...,
        [ 0.2168, -0.6093,  0.5258,  ..., -1.0164,  0.1211,  1.9200],
        [-2.4610,  1.9383,  0.2224,  ..., -0.5238, -0.5009,  1.7540],
        [-1.0813,  0.5732,  0.4036,  ...,  0.2748, -0.8362, -0.4249]],
       requires_grad=True)

In [204]:

triplet_loss = torch.nn.TripletMarginLoss(margin=1.0, p=2)
input1 = torch.ones(100, 128, requires_grad=True)
input2 = torch.ones(100, 128, requires_grad=True)
input3 = torch.ones(100, 128, requires_grad=True)
output = triplet_loss(input1, input2, input3)
print(output)

tensor(1., grad_fn=<DivBackward0>)


In [205]:

triplet_loss = torch.nn.TripletMarginLoss(margin=1.5, p=2)

output = triplet_loss(a, b, c)
print(output)

tensor(1.5000)


In [196]:
a = torch.tensor([[ 0.1363,  0.0113, -0.0596,  0.0282, -0.1059,  0.0260, -0.0701, -0.2259,
          0.1531,  0.0054, -0.0365, -0.0383, -0.0424, -0.0469,  0.2071, -0.0971,
          0.0502,  0.0029,  0.0452,  0.0719,  0.0628,  0.0118, -0.0093,  0.1385,
         -0.1397,  0.0964,  0.0353, -0.0682, -0.0467, -0.3310,  0.0264, -0.1988,
         -0.0432,  0.1144, -0.1263, -0.2117, -0.1079,  0.1642, -0.2457, -0.1195,
          0.1693, -0.1679,  0.1961,  0.1845,  0.2603, -0.1066, -0.2817, -0.1011,
         -0.0417,  0.0040, -0.2399, -0.1164,  0.1982, -0.0878,  0.1864,  0.1087,
          0.1500, -0.1382,  0.1330, -0.0558,  0.0963,  0.1538,  0.0050,  0.0464,
         -0.2659,  0.1258, -0.0154, -0.0836, -0.0388,  0.0388,  0.1189, -0.0828,
         -0.0559, -0.0996,  0.0310, -0.1683,  0.2173, -0.0426,  0.0586,  0.2255,
          0.2025, -0.1172,  0.0059,  0.2120, -0.0191,  0.1094,  0.0766,  0.2294,
          0.0852,  0.0571, -0.0893,  0.0068, -0.0228,  0.2285, -0.0037,  0.0792,
          0.0093, -0.1595, -0.1961, -0.0341],
        [ 0.1548, -0.0387, -0.1999, -0.1556, -0.1848, -0.0206, -0.0262, -0.2659,
          0.2298, -0.1447, -0.0614,  0.1784, -0.0973,  0.0241,  0.2911, -0.1149,
          0.1526,  0.0368, -0.0837,  0.1373,  0.1146, -0.0446, -0.0594,  0.2298,
         -0.0397, -0.0303, -0.0208,  0.0302, -0.1410, -0.1798,  0.1290, -0.1978,
          0.0890,  0.0757,  0.0245,  0.0380, -0.2107,  0.1709, -0.1012,  0.0131,
          0.0706, -0.0449,  0.1409,  0.1422,  0.1422,  0.0402, -0.1826, -0.1425,
         -0.1610,  0.0790, -0.1241,  0.1752,  0.1052,  0.1451,  0.1418, -0.0566,
          0.0332, -0.0607, -0.0510, -0.0026,  0.1164,  0.2951, -0.0350,  0.1688,
         -0.1955,  0.0907,  0.0386, -0.0665,  0.1748, -0.1150, -0.0026, -0.0086,
         -0.0610,  0.1016,  0.0558, -0.2300,  0.1772, -0.0852,  0.1028,  0.0436,
          0.0816, -0.1732,  0.0612,  0.0869, -0.0410,  0.1715,  0.1893,  0.0248,
         -0.1795,  0.1591, -0.0182,  0.1423,  0.1678, -0.1095, -0.0453,  0.0370,
          0.2037, -0.0982, -0.1196,  0.0307],
        [ 0.0820,  0.0133, -0.0846, -0.0380,  0.0090, -0.0748, -0.0414, -0.2602,
          0.0944, -0.0566, -0.1046,  0.0524, -0.0099, -0.0681,  0.1688, -0.0486,
          0.0445,  0.0627,  0.0903, -0.0039,  0.0307, -0.1098,  0.0712,  0.1032,
         -0.0087,  0.1436, -0.0189, -0.0896,  0.0233, -0.1702,  0.0900, -0.1432,
          0.0385,  0.0859, -0.0502, -0.0360, -0.1720,  0.0985, -0.2647, -0.2246,
          0.1003, -0.1519,  0.2766,  0.0694,  0.2062,  0.0668, -0.1360, -0.0332,
          0.0065,  0.0604, -0.1388, -0.0262,  0.1934, -0.1124,  0.1694,  0.0269,
          0.1093, -0.1129,  0.0099, -0.1131, -0.0505,  0.3011, -0.1178, -0.0148,
         -0.2987,  0.1668, -0.0062, -0.1955, -0.0585, -0.0730,  0.0146,  0.0401,
          0.0122,  0.0062,  0.0355, -0.1504,  0.1864,  0.0236,  0.0342,  0.1521,
          0.1767, -0.0900,  0.0076,  0.2432, -0.1220,  0.0695,  0.0084,  0.1853,
          0.0351, -0.0136, -0.0534,  0.0303, -0.0557,  0.1299, -0.0204,  0.1005,
          0.0553, -0.1120, -0.1409,  0.0416]])
b = torch.tensor([[ 0.1526,  0.2804, -0.2120,  0.0575, -0.3247, -0.0729,  0.1697,  0.0724,
          0.2956,  0.0321, -0.1949,  0.0866,  0.0953,  0.0365, -0.0496,  0.0297,
          0.2244, -0.1805, -0.1467, -0.0239, -0.0543, -0.0397, -0.1199,  0.3786,
         -0.2114,  0.0465, -0.0718, -0.1463,  0.2987,  0.1032,  0.0595, -0.1713,
          0.1411,  0.0719, -0.0021, -0.3210,  0.0509, -0.0811,  0.0668, -0.1703,
          0.0015,  0.1325,  0.1772, -0.2189,  0.1058,  0.2454,  0.2368, -0.1443,
          0.3861,  0.0350, -0.2625,  0.0333,  0.2045,  0.0040,  0.3138, -0.0047,
         -0.1499, -0.0465,  0.2961, -0.0249, -0.0471, -0.2140, -0.1896,  0.1802,
         -0.3443,  0.1109,  0.1487, -0.1272, -0.0136, -0.2981, -0.1228, -0.0780,
          0.1650, -0.1080, -0.1364,  0.1736,  0.1143, -0.0834, -0.0719, -0.1113,
          0.0075, -0.0752, -0.1076, -0.0004, -0.0216,  0.1233, -0.3600, -0.3550,
          0.1397,  0.0073, -0.2611, -0.3920,  0.5250, -0.0162,  0.0871, -0.1048,
          0.1677, -0.0369, -0.0124,  0.1617],
        [-0.1420,  0.0893,  0.0670,  0.0419, -0.1247,  0.0413, -0.1398, -0.0679,
         -0.0554, -0.0521, -0.2247, -0.0596,  0.1372,  0.0314,  0.2043, -0.0755,
          0.0819, -0.0227,  0.0582,  0.0725,  0.2803, -0.2341,  0.0085, -0.0119,
          0.1290,  0.0237,  0.2280, -0.0133, -0.0041, -0.1650,  0.0465,  0.0101,
         -0.1695,  0.2486,  0.2694, -0.0528,  0.0950,  0.0389, -0.0668,  0.2956,
         -0.1601, -0.0438, -0.1789, -0.0407, -0.3442, -0.1940,  0.1894, -0.3450,
          0.2085, -0.1235, -0.2606, -0.0091,  0.1313, -0.2374,  0.0516, -0.3153,
          0.0474,  0.0201,  0.0657, -0.1060, -0.1679, -0.1757,  0.1601, -0.1101,
         -0.0323,  0.0912,  0.1010, -0.3084,  0.0751,  0.2929,  0.0026,  0.3653,
          0.1254, -0.1062, -0.1657, -0.0867,  0.2986,  0.1058,  0.0362, -0.4296,
         -0.3833, -0.1898, -0.0216, -0.0133,  0.1433, -0.1829,  0.0903, -0.0361,
          0.0169, -0.2497, -0.0120,  0.1741, -0.1847,  0.2413, -0.0836, -0.0914,
         -0.0170, -0.0257, -0.2868,  0.1810],
        [ 0.2363,  0.1262, -0.2488,  0.2324, -0.2535,  0.0622,  0.2173,  0.0837,
          0.1123,  0.0688,  0.0745, -0.0414,  0.0681, -0.0551,  0.2041,  0.0842,
          0.1910,  0.0588, -0.2580, -0.1770, -0.0482, -0.3024,  0.0888,  0.1417,
         -0.1886, -0.1174, -0.1539, -0.0243,  0.1445,  0.1723, -0.1015, -0.2115,
          0.2061,  0.1497,  0.0039, -0.0960,  0.0105, -0.0709, -0.0279, -0.0869,
         -0.2393,  0.0706,  0.1627, -0.2376, -0.2062,  0.2481,  0.0749, -0.2743,
          0.4488, -0.1390, -0.1759,  0.1344,  0.3236,  0.0993,  0.2423,  0.0546,
         -0.0401, -0.0897,  0.3704, -0.0676, -0.3294, -0.3804, -0.2494,  0.0068,
          0.0129, -0.1113,  0.3074, -0.2610, -0.1175, -0.1416, -0.1150,  0.2683,
          0.1521,  0.2263, -0.0537,  0.1827,  0.0633, -0.2029, -0.0794, -0.1666,
          0.1775, -0.0195,  0.0394,  0.0693,  0.0362, -0.0446, -0.0487, -0.2910,
         -0.1094, -0.0302, -0.1512, -0.0794,  0.0543,  0.1289,  0.1107, -0.2292,
          0.0633,  0.1400, -0.0271, -0.0485]])
c = torch.tensor([[ 0.1526,  0.2804, -0.2120,  0.0575, -0.3247, -0.0729,  0.1697,  0.0724,
          0.2956,  0.0321, -0.1949,  0.0866,  0.0953,  0.0365, -0.0496,  0.0297,
          0.2244, -0.1805, -0.1467, -0.0239, -0.0543, -0.0397, -0.1199,  0.3786,
         -0.2114,  0.0465, -0.0718, -0.1463,  0.2987,  0.1032,  0.0595, -0.1713,
          0.1411,  0.0719, -0.0021, -0.3210,  0.0509, -0.0811,  0.0668, -0.1703,
          0.0015,  0.1325,  0.1772, -0.2189,  0.1058,  0.2454,  0.2368, -0.1443,
          0.3861,  0.0350, -0.2625,  0.0333,  0.2045,  0.0040,  0.3138, -0.0047,
         -0.1499, -0.0465,  0.2961, -0.0249, -0.0471, -0.2140, -0.1896,  0.1802,
         -0.3443,  0.1109,  0.1487, -0.1272, -0.0136, -0.2981, -0.1228, -0.0780,
          0.1650, -0.1080, -0.1364,  0.1736,  0.1143, -0.0834, -0.0719, -0.1113,
          0.0075, -0.0752, -0.1076, -0.0004, -0.0216,  0.1233, -0.3600, -0.3550,
          0.1397,  0.0073, -0.2611, -0.3920,  0.5250, -0.0162,  0.0871, -0.1048,
          0.1677, -0.0369, -0.0124,  0.1617],
        [-0.1420,  0.0893,  0.0670,  0.0419, -0.1247,  0.0413, -0.1398, -0.0679,
         -0.0554, -0.0521, -0.2247, -0.0596,  0.1372,  0.0314,  0.2043, -0.0755,
          0.0819, -0.0227,  0.0582,  0.0725,  0.2803, -0.2341,  0.0085, -0.0119,
          0.1290,  0.0237,  0.2280, -0.0133, -0.0041, -0.1650,  0.0465,  0.0101,
         -0.1695,  0.2486,  0.2694, -0.0528,  0.0950,  0.0389, -0.0668,  0.2956,
         -0.1601, -0.0438, -0.1789, -0.0407, -0.3442, -0.1940,  0.1894, -0.3450,
          0.2085, -0.1235, -0.2606, -0.0091,  0.1313, -0.2374,  0.0516, -0.3153,
          0.0474,  0.0201,  0.0657, -0.1060, -0.1679, -0.1757,  0.1601, -0.1101,
         -0.0323,  0.0912,  0.1010, -0.3084,  0.0751,  0.2929,  0.0026,  0.3653,
          0.1254, -0.1062, -0.1657, -0.0867,  0.2986,  0.1058,  0.0362, -0.4296,
         -0.3833, -0.1898, -0.0216, -0.0133,  0.1433, -0.1829,  0.0903, -0.0361,
          0.0169, -0.2497, -0.0120,  0.1741, -0.1847,  0.2413, -0.0836, -0.0914,
         -0.0170, -0.0257, -0.2868,  0.1810],
        [ 0.2363,  0.1262, -0.2488,  0.2324, -0.2535,  0.0622,  0.2173,  0.0837,
          0.1123,  0.0688,  0.0745, -0.0414,  0.0681, -0.0551,  0.2041,  0.0842,
          0.1910,  0.0588, -0.2580, -0.1770, -0.0482, -0.3024,  0.0888,  0.1417,
         -0.1886, -0.1174, -0.1539, -0.0243,  0.1445,  0.1723, -0.1015, -0.2115,
          0.2061,  0.1497,  0.0039, -0.0960,  0.0105, -0.0709, -0.0279, -0.0869,
         -0.2393,  0.0706,  0.1627, -0.2376, -0.2062,  0.2481,  0.0749, -0.2743,
          0.4488, -0.1390, -0.1759,  0.1344,  0.3236,  0.0993,  0.2423,  0.0546,
         -0.0401, -0.0897,  0.3704, -0.0676, -0.3294, -0.3804, -0.2494,  0.0068,
          0.0129, -0.1113,  0.3074, -0.2610, -0.1175, -0.1416, -0.1150,  0.2683,
          0.1521,  0.2263, -0.0537,  0.1827,  0.0633, -0.2029, -0.0794, -0.1666,
          0.1775, -0.0195,  0.0394,  0.0693,  0.0362, -0.0446, -0.0487, -0.2910,
         -0.1094, -0.0302, -0.1512, -0.0794,  0.0543,  0.1289,  0.1107, -0.2292,
          0.0633,  0.1400, -0.0271, -0.0485]])